service: koebutter-fetcher
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
  deploymentBucket: serverless-upload-ap-northeast-1
  versionFunctions: false
  iamRoleStatements:
    - Effect: "Allow"
      Action: ["s3:PutObject", "s3:GetObject"]
      Resource: { Fn::Join : ["", ["arn:aws:s3:::", { Ref : Bucket }, "/*" ] ]  }

functions:
  fetch:
    handler: handler.fetch
    timeout: 300
    events:
      - schedule: cron(0 8 * * ? *)

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: koebutter-fetcher